services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-api
    env_file:
      - .env
    ports:
      - "1000:8000"
    volumes:
      - /home/quikle/media:/app/media
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
